# This is a basic workflow to help you get started with Actions

name: build docker image

# Controls when the action will run.
on:
  push:
    branches:
      - release
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push samge_wx_bot
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          # Required architecture, all available architectures can be obtained in Available platforms step
          platforms: linux/amd64
          # mirror push time
          push: ${{ github.event_name != 'pull_request' }}
          # tag multiple lists
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/samge_wx_bot:${{ steps.date.outputs.today }}
            ${{ secrets.DOCKERHUB_USERNAME }}/samge_wx_bot:v2
            ${{ secrets.DOCKERHUB_USERNAME }}/samge_wx_bot:latest
            